baseurl:
produrl: https://russelljkennedy.github.io/victimofvincent
name: A Victim of Vincent
description: Find the latest offerings and sacrifices from the Victim of Vincent Vault.
url: https://russelljkennedy.github.io/victimofvincent
public_url: https://www.victimofvincent.com
kramdown:
  auto_ids: false
